# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\"0\n\x0b\x41uthRequest\x12!\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x0c.Credentials\".\n\x0b\x43redentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"=\n\rOptionalToken\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\x15\n\rsession_token\x18\x02 \x01(\t25\n\x0b\x41uthService\x12&\n\x04\x61uth\x12\x0c.AuthRequest\x1a\x0e.OptionalToken\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUTHREQUEST']._serialized_start=18
  _globals['_AUTHREQUEST']._serialized_end=66
  _globals['_CREDENTIALS']._serialized_start=68
  _globals['_CREDENTIALS']._serialized_end=114
  _globals['_OPTIONALTOKEN']._serialized_start=116
  _globals['_OPTIONALTOKEN']._serialized_end=177
  _globals['_AUTHSERVICE']._serialized_start=179
  _globals['_AUTHSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
